services:
  app:
    image: weather-flask:latest
    container_name: weather-flask
    ports:
      - "8081:5001"  # Map host port 8081 to container port 5001
    environment:
      DOTNET_URL: weatherapi
      DOTNET_PORT: 8080
    volumes:
      - C:/Users/administrator/documents/api-flask/.env:/app/.env
      
  webapiapp:
    image: weatherapi:latest # Replace with your Docker image name and tag
    container_name: weatherapi
    ports:
      - "8080:8080" # Maps port 8080 on the host to port 8080 in the container
    environment:
      ASPNETCORE_ENVIRONMENT: Production # Set the application environment
      CUSTOM_SETTING: HelloWorld         # Example custom environment variable
    volumes:
      - ./logs:/app/logs # (Optional) Maps a local directory for application logs
